# Generated by Django 3.2.13 on 2022-11-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieNm', models.CharField(max_length=100)),
                ('movieNmEn', models.CharField(max_length=100)),
                ('showTm', models.IntegerField()),
                ('prdtYear', models.IntegerField()),
                ('nations', models.TextField()),
                ('genres', models.TextField()),
                ('directors', models.TextField()),
                ('actors', models.TextField()),
            ],
        ),
    ]
