# Generated by Django 3.2.13 on 2022-11-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_tmdb_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmdb_movie',
            name='poster_path',
            field=models.TextField(blank=True),
        ),
    ]
