# Generated by Django 3.2.13 on 2022-11-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_tmdb_movie_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmdb_movie',
            name='poster_path',
            field=models.TextField(null=True),
        ),
    ]
